### ISSUE TITLE
No output when using `viddy` or `hwatch` watching tools

### ISSUE THREAD

**Issue by onedr0p** [kubecolor/kubecolor#107]
# Expected Behavior

For the below commands to work, currently there is no output in the shell when using either. This used to work before 0.3.0.

# Current Behavior

There is no command output using the below tools with kubecolor

https://github.com/sachaos/viddy

```
viddy -d -n 2 --shell /opt/homebrew/bin/fish kubecolor get po
```

https://github.com/blacknon/hwatch

```
hwatch -n 2 -s '/opt/homebrew/bin/fish -c "source ~/.config/fish/config.fish" {COMMAND}' kubecolor get po
```

## Context

This used to work on the previous release of kubecolor.

* Operating System: MacOS / Installed all CLI tools with Brew
* kubectl version: v1.29.3
* kubecolor version: 0.3.0

**Comment by applejag** [comment]
When we released v0.3.0 it had a bug where plain (uncolored) output was not shown. We fixed this and republished v0.3.0 right after.

It's possible you first got the buggy version 0.3.0, and then got the updated 0.3.0.

Sorry for the inconvenience

**Comment by onedr0p** [comment]
@applejag I believe this issue is happening with the Termux package too, does it make since to make a new release to get rid of all the weirdness we're seeing?

**Comment by applejag** [comment]
> @applejag I believe this issue is happening with the Termux package too, does it make since to make a new release to get rid of all the weirdness we're seeing?
> 
> Publishing over an existing tag should never be a thing IMO, they should be immutable.

I created https://github.com/termux/termux-packages/pull/19776 but it hasn't been merged yet.

Might consider adding another tag.

I agree that they should be immutable. It was a onetime mishap

**Comment by applejag** [comment]
v0.3.1 has been released: https://github.com/kubecolor/kubecolor/releases/tag/v0.3.1

**Comment by onedr0p** [comment]
Perfect, thanks!

**Comment by luebken** [comment]
I'm running into same problem. 

shows color
```
kubecolor get pods
```
doesn't show color: 
```
watch --color kubecolor get pods
```
I'm running
```
kubecolor --kubecolor-version
v0.4.0
```

**Comment by applejag** [comment]
@luebken When running inside `watch`, kubecolor can't figure out if the output has color support or not. What you can do is to force it to use colors like so:

```bash
watch --color kubecolor get pods --force-colors
```

If you're making use of truecolor color codes in your themes then you can force kubecolor to use that:


```bash
watch --color kubecolor get pods --force-colors=truecolor
```

**Comment by onedr0p** [comment]
It also looks like `--force-colors=auto` works as well with viddy, any chance this could be changed to be the default  @applejag ?

**Comment by applejag** [comment]
Nah sorry, having it force colors by default would mess with when you're piping commands.

Such as:

```bash
kubectl get pods > output.txt
```

**Comment by applejag** [comment]
Btw a small plug: a nicer way to do `kubectl get --watch` is by using https://github.com/applejag/kubectl-klock :)

**Comment by onedr0p** [comment]
Nice plug, I'll give that a drive for awhile
