### ISSUE TITLE
oc rsh breaks when using kubecolor

### ISSUE THREAD

**Issue by dijarvrella** [kubecolor/kubecolor#108]
# Expected Behavior

One should be able to successfully get a container shell without the presentation be screwed

# Current Behavior

I can't work when using kubecolor is set as an alias for oc command as the shell is kind of in a corrupted presentation

![image](https://github.com/kubecolor/kubecolor/assets/121172376/7e2940a1-6dae-4d11-8eea-a70ee94a5c6a)

This is how it works when the alias is removed:
![image](https://github.com/kubecolor/kubecolor/assets/121172376/ee75b730-f6f0-41f6-8328-7f090731d00c)

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: MacOS 14.4.1 (23E224)
* kubectl version: Client Version: 4.14.3
* kubecolor version: 0.3.0
* zsh 5.9 (arm-apple-darwin23.0.0)

**Comment by applejag** [comment]
Thanks for reporting this @dijarvrella!

Definitely a bug

**Comment by dijarvrella** [comment]
Hi @applejag and @prune998 I know you fixed this problem as I tested as soon as you merged the PR but I see this resurfacing. Can you please also confirm(see image below for reference):

![image](https://github.com/kubecolor/kubecolor/assets/121172376/fbf81548-0738-4f04-81f4-3583b3dfed0b)

**Comment by prune998** [comment]
Thanks for reporting back.
Can you just confirm the exact command executed by `orsh` alias ? 
The patch for the `rsh` command is still in the code at https://github.com/kubecolor/kubecolor/blob/main/command/subcommand.go#L68, so something else is at play here...

Your shell / terminal also seems to be adding coloring... could it be a side effect ? 
Can you do the same but using plain `oc` (with no alias for `kubecolor` ? 

(I have no OpenShift to test with so far... Not sure about @applejag ... )

**Comment by applejag** [comment]
There we go, @dijarvrella. That should solve it :)

@prune998 I think we can do a v0.3.3 release. Might take a little while before our other PRs are ready to be merged

**Comment by prune998** [comment]
Release done. Please upgrade to v0.3.3

**Comment by dijarvrella** [comment]
Sorry guys, didn't have the chance to see the messages as I was very busy. Works perfectly now! Thank you and great job 👏🏻🙌🏻
