### ISSUE TITLE
kubectl plugin getting colorized

### ISSUE THREAD

**Issue by applejag** [kubecolor/kubecolor#109]
Thanks for maintaining this cool project. I have a question about Krew and the statement that subcommands are not colored. In https://github.com/kubecolor/kubecolor/pull/8 this feature has been added. As far as I understand it, it looks for the path prefix kubectl- to determine if its a subcommand. But this does not work for me, as can be seen in the screenshot below. Is this a bug or is it only possible if the plugin is started directly as a script?

Example
![Screenshot 2024-04-22 at 15 44 55](https://github.com/kubecolor/kubecolor/assets/75072836/3d5b88ab-5926-4820-a914-753bb38d9c8e)

In my case, fzf is not able to show a preview of the output because of this.
```
DEBUG=true ./kubectl-node_connect
+ set -eou pipefail
+ IFS='
	'
+ kubecolor get pods
+ fzf
```

kubecolor 0.3.0 (Brew)
kubectl v1.30.0 (Brew)
fzf 0.50.0 (Brew)

_Originally posted by @larsgerber in https://github.com/kubecolor/kubecolor/issues/65#issuecomment-2069588063_

**Comment by larsgerber** [comment]
Hello @applejag 

Thanks for creating the new issue. If I use the underscore or the plain parameter like you said, my fzf preview works again.

<img width="801" alt="Screenshot 2024-04-22 at 19 46 20" src="https://github.com/kubecolor/kubecolor/assets/75072836/bca31eb4-91c0-4d89-b89e-2764f906ed32">

I think it should also accept the hyphen, as this is the correct naming of a plugin according to the Krew Plugin Naming Guide https://krew.sigs.k8s.io/docs/developer-guide/develop/naming-guide/.

I'm fairly new to Go, but I'm happy to create a MR that supports both if that would be helpful.

**Comment by applejag** [comment]
Just to do an "uhm actually": this issue is not about krew guidelines, but instead of how kubectl resolves plugin names.

As I [commented in the PR](https://github.com/kubecolor/kubecolor/pull/110#discussion_r1576257799):

> This is very interesting, and made me question if kubectl really acts like this. And you're right, it does.
> 
> After looking at their source code and doing some testing, it seems to handle it like this:
> 
> * `kubectl do some thing`
>       
>   * try exec `kubectl-do-some-thing`
>   * try exec `kubectl-do-some thing`
>   * try exec `kubectl-do some thing`
> 
> * `kubectl do-some thing`
>      
>   * try exec `kubectl-do_some-thing`
>   * try exec `kubectl-do_some thing`
> 
> * `kubectl do-some-thing`
>       
>   * try exec `kubectl-do_some_thing`
> 
> (Source: https://github.com/kubernetes/kubectl/blob/d0e936c703558421df2ef367a7c8c1c5972e5c3c/pkg/cmd/cmd.go#L260-L307)

Confirmed that this is buggy behavior in kubecolor

**Comment by larsgerber** [comment]
Hello @applejag 

Sorry for the late reply. I'll definitely look into this, but as I wrote, I'm fairly new to Go so I need to learn some principles before I can tackle this issue. So far I've been able to understand the code and do some manul testing.

**Comment by larsgerber** [comment]
Hello @applejag

I've been working on the solution for a week now, but haven't made much progress so far. So if anyone wants to jump in, feel free to do so. I don't want to prevent anyone from working on this. Otherwise I will continue to work on this issue.

**Comment by applejag** [comment]
@larsgerber yeah no worries.

None of us maintainers have a "reliable schedule" of when we contribute. It just when we feel like it. But good to know that this issue is open next time someone has a "spike of contributions" unless you're already done with it by then.
