### ISSUE TITLE
Explain command in the kubectl v1.27.x

### ISSUE THREAD

**Issue by jtyr** [kubecolor/kubecolor#11]
# Expected Behavior

I would expect that `kubecolor` formats the ourput of the `explain` command correctly.

# Current Behavior

Currently the `kubecolor` doesn't display any "DESCRIPTION" even though `kubectl` does:

```console
$ ~/bin/kubectl-1.27.2 explain pod.spec.schedulerName
KIND:       Pod
VERSION:    v1

FIELD: schedulerName <string>

DESCRIPTION:
    If specified, the pod will be dispatched by specified scheduler. If not
    specified, the pod will be dispatched by default scheduler.
```

```console
$ export KUBECTL_COMMAND=~/bin/kubectl-1.27.2
$ go run cmd/kubecolor/main.go explain pod.spec.schedulerName
KIND:       Pod
VERSION:    v1

FIELD: schedulerName <string>:

DESCRIPTION:
```

I believe that's because `kubecolor` is expecting the "DESCRIPTION" to be indented by [5 spaces](https://github.com/kubecolor/kubecolor/blob/23a17b7906fc8258878f306ff70a8ddf545a4dbf/printer/kubectl_explain.go#L22) but the `kubeclt-1.27.2` output shows only 4 spaces of indentation. Any previous version of `kubectl` had 5 spaces:

```console
$ ~/bin/kubectl-1.26.5 explain pod.spec.schedulerName
KIND:     Pod
VERSION:  v1

FIELD:    schedulerName <string>

DESCRIPTION:
     If specified, the pod will be dispatched by specified scheduler. If not
     specified, the pod will be dispatched by default scheduler.
```

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Arch Linux
* kubectl version: 1.27.2
* kubecolor version: build from the main branch

**Comment by applejag** [comment]
Thanks for the great issue! Nice find!

We're fixing this with #21
