### ISSUE TITLE
Project unmaintained?

### ISSUE THREAD

**Issue by applejag** [kubecolor/kubecolor#13]
Hello! It seems that this project is unmaintained.

Is this correct?

I find it ironic, as you created this GitHub org and repo because the original author was quite inactive (https://github.com/hidetatz/kubecolor/issues/95). That repo has now been marked as archived, without a clear explanation.

But now this project is also seems unmaintained.

**Comment by junaid-ali** [comment]
@prune998 are you open to adding more maintainers?

**Comment by prune998** [comment]
I'm totally opened and I even called for it :) 
This project is not un-maintained... I'm not sure why I did not get this message. What do you need to maintain ?

**Comment by prune998** [comment]
I'm reviewing the PRs. The build is also not working, I need to update action versions and all... but it's not un-maintained, it's just taking some time :)
sorry for that.
@applejag want to be added as a maintainter ? @junaid-ali ?

**Comment by applejag** [comment]
@prune998 hehe sorry for the accusation. Unmaintained has a quite fuzzy meaning around these waters.

Yes sure, I'd like to be maintainer. Do you have something in mind for what's a go/no-go for types of contributions? What part do you need help maintaining? Code contributions? Reviewing? Keeping up to date with Go releases?

**Comment by prune998** [comment]
all of that :)

reviewing the PR, testing things, improving the app... 
For example, one of the improvements we could do would be supporting custom color scheme... but I think it's a big one needing a lot of reformating of the code. 
I don't have time for improving the code right now, but again, PRs welcome.

It seems I don't have time to review the PRs. stop :) 
But I should have reviewed them anyways... it's just I didn't got the notification. It should be ok now and I will review the remaining ones.

But again, if you have some time to help, you're welcome.

**Comment by applejag** [comment]
Sounds alright. I'm still a heavy user of this, and have been maintaining my own fork just for myself. But I'll direct that effort here then.

If I were to contribute code, do you have a preferred process? Just a basic PR flow I assume. If you don't have time for reviewing, would it be OK to merge without your review?

**Comment by prune998** [comment]
I'm going to add you as a maintainer, but I prefer to review PRs. I WILL find the needed time, and you document the PR well it should be flawless :)

**Comment by applejag** [comment]
Perfect!

I'm closing this issue as solved now :)

**Comment by junaid-ali** [comment]
> want to be added as a maintainter ? @junaid-ali ?
Sorry, have been reading the comments via email. Congrats @applejag .

Please do add me if you need another one :)
