### ISSUE TITLE
KUBECOLOR_CONFIG must be a directory rather than a file

### ISSUE THREAD

**Issue by cbandy** [kubecolor/kubecolor#137]
# Expected Behavior

I expected this example in the readme to work:

https://github.com/kubecolor/kubecolor/blob/7d4c2edd1f47b5276ae996586c545822bd44038e/README.md?plain=1#L716-L720

# Current Behavior

`KUBECOLOR_CONFIG` must point to a _directory_ that contains a `color.yaml` file.

## Context

Introduced in #59.

* Operating System: macOS Sonoma 14.5
* kubectl version: 1.30.1
* kubecolor version: 0.3.3

**Comment by cbandy** [comment]
If the intent is for `KUBECOLOR_CONFIG` to refer to a file (and forego any "searching" for files), perhaps [viper.SetConfigFile](https://pkg.go.dev/github.com/spf13/viper#SetConfigFile):

https://github.com/kubecolor/kubecolor/blob/7d4c2edd1f47b5276ae996586c545822bd44038e/config/config.go#L53

```go
	if path := os.Getenv("KUBECOLOR_CONFIG"); path != "" {
		v.SetConfigFile(path)
	} else if homeDir, err := os.UserHomeDir(); err == nil {
		// ~/.kube/color.yaml
		v.AddConfigPath(filepath.Join(homeDir, ".kube"))
	}
```

**Comment by applejag** [comment]
You're right. That was the intention. Will change to SetConfigFile
