### ISSUE TITLE
Make next release at least v0.0.26

### ISSUE THREAD

**Issue by applejag** [kubecolor/kubecolor#15]
# Expected Behavior

Next release of kubecolor is at least v0.0.26, or perhaps v0.1.0.

# Current Behavior

Current latest version of this repo is v0.0.21. So we need to be careful not confuse v0.0.22-0.0.25 with https://github.com/hidetatz/kubecolor/releases

## Context

Package maintainers do not make a distinction between the hidetatz kubecolor or this repo.

While both repos has diverged a little from each other, it is important to not cause unnecessary confusion, as the two projects do kind of share the same "versioning space", so to speak.

**Comment by prune998** [comment]
we're going to cut `v0.1.0`
