### ISSUE TITLE
kubectl plugin output is always colored

### ISSUE THREAD

**Issue by crabique** [kubecolor/kubecolor#170]
### Expected behavior

Output from kubectl plugins that get colored is not consistent with native kubectl coloring rules in terms of detecting TTYs. The output is always colored, even when it's going into a pipe or a subshell.

### Current behavior

```console
$ type kubectl
kubectl is an alias for kubecolor

$ kubectl get secret test --template '{{ base64decode .data.pass }}' | bat -A # good
testpassword
  
$ kubectl view-secret test pass | bat -A # bad, not usable in $() because of the escape seqs
␛[32mtestpassword␛[0m␊
  
$ \kubectl view-secret test pass | bat -A # good
testpassword
```

### Package manager

Homebrew

### What operating system are you running?

Mac

### Kubectl and kubecolor version

```yaml
Client Version: v1.31.0
Kustomize Version: v5.4.2
```

**Comment by applejag** [comment]
Thanks for reporting this @crabique !

I've been able to reproduce the bug. Thanks for the clear steps.

This issue does not appear in the main branch. When `git bisect`ing, I see that #110 was the PR that fixed this issue.

We're preparing for the release of v0.4.0, which should drop soon. So you could either wait for v0.4.0, or you could go for using the main branch for now: `go install github.com/kubecolor/kubecolor@main`

Closing as duplicate
