### ISSUE TITLE
First line of `get` output is treated as table header in name/custom-columns output mode

### ISSUE THREAD

**Issue by crabique** [kubecolor/kubecolor#172]
### Expected behavior

When doing `k get <something> -o name` or `k get <something> -o custom-columns=:.metadata.name`, the result should be all displayed uniformly as the output is a list, not a table.

### Current behavior

First line is printed in bold, as if it has any special meaning compared to the rest of the list.

```console
$ k --force-colors get svc -l ... -o name | bat -A
  ␛[1mservice/prometheus-monitoring-kube-coredns␛[0m␊
  ␛[37mservice/prometheus-monitoring-kube-kube-controller-manager␛[0m␊
  ␛[37mservice/prometheus-monitoring-kube-kube-etcd␛[0m␊
  ␛[37mservice/prometheus-monitoring-kube-kube-scheduler␛[0m␊
```

### Package manager

Homebrew

### What operating system are you running?

Mac

### Kubectl and kubecolor version

```yaml
$ kubecolor version --client
Client Version: v1.31.0
Kustomize Version: v5.4.2
```

**Comment by applejag** [comment]
Hello @crabique! Great bug report!

If you want you can try tackle this yourself.

Otherwise this will be delayed until after v0.4.0 as we're trying to get that released soon
