### ISSUE TITLE
Package as snap

### ISSUE THREAD

**Issue by jadolg** [kubecolor/kubecolor#173]
### Description

I'd like to be able to install kubecolor as a [Ubuntu snap](https://snapcraft.io/). Goreleaser is able to [build and deploy](https://goreleaser.com/customization/snapcraft/) snaps. 

### Additional context

I can help with this if needed.

**Comment by applejag** [comment]
Definitely something we can look into, but I'm a bit weary as kubecolor is a CLI wrapper and Snaps don't really have support for that.

Would the `kubecolor` snap contain a version of `kubectl`? Does this mean if you're using the `kubecolor` snap then you can't use your other `kubectl` plugins? IIRC there's no snap interface for allowing "starting other processes on your computer"

Would we need to resort to a `--classic` snap confinement type? Maybe that's find as the `kubectl` snap also requires that. But would be nice not do have to go down that route.

Kubecolor needs access to run kubectl, and nothing else. Throwing in `classic` confinement feels super overkill as kubecolor does not need network or file access (except for `~/.kube/color.yaml`), and feels like misusing snaps.

The only gain would then be the updating procedure and none of snap's sandboxing features. Which may be fine. What do you think?

**Comment by jadolg** [comment]
You are right. Applying for classic confinement in the snap store is also a complete waste of time in most cases.
