### ISSUE TITLE
Quote characters swallowed in ConfigMap inline data

### ISSUE THREAD

**Issue by cmeury** [kubecolor/kubecolor#179]
### Expected behavior

The configmap is printed with correct data.

### Current behavior

Create a ConfigMap:

```shell
cat <<EOF | kubectl apply -f -
apiVersion: v1
data:
  data: |
    foo = "bar"
kind: ConfigMap
metadata:
  name: test
EOF
```

Then, display it:

```bash
kubecolor get configmap test -oyaml
apiVersion: v1
data:
  data: |
    foo = "bar
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"data":"foo = \"bar\"\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"test","namespace":"spire"}}
  creationTimestamp: "2024-09-12T14:32:04Z"
  name: test
  namespace: spire
  resourceVersion: "79984219"
  uid: 8206bfef-16ac-460f-a2a1-031e332fdeed
```

* Spot the missing quote at the end of the value _bar_.

## Screenshots

![image](https://github.com/user-attachments/assets/97d60dbc-2cdc-4146-a726-d5bdd18cb522)

### Package manager

Installed via `go install`.

### What operating system are you running?

Ubuntu Linux 24.04
zsh shell 5.8.1

### Kubectl and kubecolor version

```yaml
kubecolor version
Client Version: v1.29.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.7
Kubecolor Version: v0.4.0
```

**Comment by applejag** [comment]
Hah, curious find! Thanks for reporting this @cmeury 

We're in need of sore fuzz testing in this area. Will look into this
