### ISSUE TITLE
kubectl get -w has no output

### ISSUE THREAD

**Issue by zhangzujian** [kubecolor/kubecolor#38]
# Expected Behavior

Please describe the behavior you are expecting

# Current Behavior

```console
$ kubecolor get po -o wide
NAME    READY   STATUS    RESTARTS   AGE   IP              NODE    NOMINATED NODE   READINESS GATES
web-0   1/1     Running   0          3h    10.16.119.193   node1   <none>           <none>
web-1   1/1     Running   0          61m   10.16.119.197   node1   <none>           <none>
web-2   1/1     Running   0          3h    10.16.119.195   node1   <none>           <none>

$ kubecolor get po -o wide -w
^C
```

Introduced in #29.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System:
* kubectl version:
* kubecolor version: v0.2.0

**Comment by applejag** [comment]
Hello 张祖建! Thanks for the great issue.

Will work on a fix as soon as I am back from vacation.
