### ISSUE TITLE
Color scheme isn't as pretty in v0.0.21

### ISSUE THREAD

**Issue by hussam-qasem** [kubecolor/kubecolor#4]
The Color scheme is off with v0.0.21

# Expected Behavior
<img width="845" alt="Screen Shot 2022-09-29 at 7 30 23 PM" src="https://user-images.githubusercontent.com/68053227/193088163-048825cd-7268-40d8-953e-bce24f499911.png">

# Current Behavior
<img width="843" alt="Screen Shot 2022-09-29 at 7 29 22 PM" src="https://user-images.githubusercontent.com/68053227/193088182-9e003064-46f9-4b3b-8527-7c379b35f376.png">

## Context

Upgraded to this repo to solve the [auto-completion bug](https://github.com/hidetatz/kubecolor/issues/78).

* Operating System: `Oracle Linux Server release 8.6`
* kubectl version: `v1.23.7+1.el8`
* kubecolor version: `0.0.21`

**Comment by jrpedrianes** [comment]
Hi,

In mac happen the same:

OS: `macOS Monterey 12.6`
kubectl version: `v1.25.0`
kubecolor version: `0.0.21`

**Comment by markthequark** [comment]
I also have this issue. I understand some colours were changed to white to enhance readability from this PR https://github.com/hidetatz/kubecolor/pull/40
but in the current version I have inconsistent usage of colours when running `kubecolor describe pod <pod-name>`

In the meantime I'm using [jrpedrianes's](https://github.com/jrpedrianes) fork which keeps all the original colours from v0.20 but fixes the [autocomplete issue](https://github.com/hidetatz/kubecolor/issues/78) for me.
https://github.com/jrpedrianes/kubecolor/releases/tag/v0.0.21

**Comment by prune998** [comment]
I hear the concerns. I was mixed about adding this color change, but in the end I find it readable too... 
I will look to either change the colors back to normal add a flag. colors scheme would be like the original `kubecolor` and a flag to enable colors for disabled people.

WDYT ?

**Comment by prune998** [comment]
I still feel the `new` coloring scheme is not that bad... it's really easy to spot good/bad or new/old stuff...

<img width="1546" alt="prune_arcadia__" src="https://user-images.githubusercontent.com/1110398/196044565-f3408320-e2e5-4da3-b72d-7cd8309e0598.png">

**Comment by markthequark** [comment]
To be honest I prefer the enhanced readability colour scheme, it just took some getting used to.

**Comment by prune998** [comment]
we could also color the `RESTARTS` in yellow/red after some threshold...

**Comment by hussam-qasem** [comment]
Thank you @prune998 for all your efforts.

Would you consider making all colors configurable (e.g. via a dot-file or environment variable), and let each user decide the color scheme that suits them.

<img width="824" alt="Screen Shot 2022-10-17 at 6 59 26 AM" src="https://user-images.githubusercontent.com/68053227/196086579-5922128b-9f62-4286-bc70-b2b1ed9a865d.png">

**Comment by prune998** [comment]
Hi @hussam-qasem ,

so far, the way the code is build make it really difficult to change each component's color. It would be a really big effort to change this. I'll see what I can do, and i'm always opened to review PRs too if someone want to tackle this :)

**Comment by jrpedrianes** [comment]
One thing that I notice is that the output is not the same when we are using `--all-namespaces` option. 

<img width="586" alt="Captura de Pantalla 2022-10-17 a las 19 54 28" src="https://user-images.githubusercontent.com/1927286/196259784-162bd600-8673-4108-9260-a38f7bc5be41.png">

<img width="869" alt="Captura de Pantalla 2022-10-17 a las 19 55 53" src="https://user-images.githubusercontent.com/1927286/196259814-670a2c0b-ad21-48a7-ac42-08da94d7f81a.png">

For example, in the first picture the pod name has a white colour font, but in the second one is blue, the font colour for `READY` column change between images... Is this the expected behaviour? 

**Environment**
SO: macOS
kubectl: v1.22.15
kubecolor: 0.0.21

**Comment by JulioZanette** [comment]
I really miss the old Color Schema. Any chance you can bing it back, or make it an flag as @prune998 suggestion above.

**Comment by applejag** [comment]
> One thing that I notice is that the output is not the same when we are using `--all-namespaces` option.
> 
> <img alt="Captura de Pantalla 2022-10-17 a las 19 54 28" width="586" src="https://user-images.githubusercontent.com/1927286/196259784-162bd600-8673-4108-9260-a38f7bc5be41.png">
> 
> <img alt="Captura de Pantalla 2022-10-17 a las 19 55 53" width="869" src="https://user-images.githubusercontent.com/1927286/196259814-670a2c0b-ad21-48a7-ac42-08da94d7f81a.png">
> 
> For example, in the first picture the pod name has a white colour font, but in the second one is blue, the font colour for `READY` column change between images... Is this the expected behaviour?
> 
> **Environment** SO: macOS kubectl: v1.22.15 kubecolor: 0.0.21

That is expected. Kubecolor is doing alternating coloring per column. When adding the `--all-namespaces`/`-A`, then it's adding another column at the far left, leading to the colors being shifted.

We can look into adding a special case for it, so we reduce the color mismatch.

**Comment by prune998** [comment]
Issue https://github.com/kubecolor/kubecolor/issues/9 was created to track the color schema changes, so I'm going to close this issue. 
Until we have that fully configurable, there's no point of discussing of a color change in an issue. It's down to each user preference, and the decision was made to go with a color schema that is compatible with color-blind (or color impaired) people.
I'll put some efforts to get the colors configurables ASAP. Thanks for your understanding.
