### ISSUE TITLE
breaks completion

### ISSUE THREAD

**Issue by uhthomas** [kubecolor/kubecolor#47]
# Expected Behavior

Completion for kubectl (when it's an alias to `kubecolor`) should work as normal.

# Current Behavior

Completion for kubectl no longer works.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Arch Linux
* kubectl version: v1.29.0
* kubecolor version: v0.2.1

**Comment by applejag** [comment]
Hello @uhthomas ! Thanks for reporting this.

What shell are you having issues in? Bash? Zsh? Fish?

Have you followed the docs found in the repo readme regarding completions? <https://github.com/kubecolor/kubecolor#autocompletion>

**Comment by monotek** [comment]
I have the same issue, with bash completion and using an alias for "k":

```
alias k='kubecolor'
```

Completion of namespaces work but when i try to complete "p" with tab to get to "pod" i get the following error:

```
k get pbash: 4: syntax error: invalid arithmetic operator (error token is "")

```

**Comment by applejag** [comment]
@monotek thanks for expanding! Would you mind creating a new issue about this? And also noting the version of kubectl and kubecolor that you're using?

(Kubecolor version is found out via the `--kubecolor-version` flag)

**Comment by monotek** [comment]
I think i figured it out. 
The issue is that i've created my alias with "--force-colors".
Removing it solved the issue.

**Comment by applejag** [comment]
That's interesting! The --force-colors flag should not break completion.
