### ISSUE TITLE
Feature: colorize logs

### ISSUE THREAD

**Issue by applejag** [kubecolor/kubecolor#51]
# Expected Behavior

Would be grand if kubecolor could do some simple colorizing of log lines when doing `kubecolor logs my-pod-123`.

Could be a lot of simple colorizing techniques, such as highlighting ERROR, ERR, and ERRO as bold red. Have WARNING, WRN, and WARN as orange/dark yellow, and so on.

As well as colorizing quotations `"text"` or stuff inside square brackets `[text]` to make them stand out more.

It's not a perfect solution, but it could help find some keywords in logs.

Then if the log line is a JSON or [logfmt](https://docs.appsignal.com/logging/formatting/logfmt.html) message, then apply syntax highlighting there as well. Such as in JSON to highlight the key vs value parts.

Also think timestamps should be grayed out, like using "bright black" in basic ANSI terminal coloring terms.

# Current Behavior

Logs are just green.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Linux
* kubectl version:
* kubecolor version: v0.2.2

**Comment by semihbkgr** [comment]
Hi @applejag 

moving from #70 🙂

As you explained, there are many ways to enhance log colorization. However, it's crucial to check first if the logs are already colored.

**Comment by prune998** [comment]
Well, I think we should just not colorize any logs at all. I guess the green coloring is a bug and we can correct it.

There's this wonderful application called `Stern` (https://github.com/stern/stern) that will do log coloring better and will handle all the use-cases.
Any PR will be welcome but it's the feature with the least priority on my list :)

**Comment by applejag** [comment]
I think this could be fun to tackle. :)

Besides, I see that Stern is written in Go, so maybe we could import Stern as a dependency? I don't see much coloring logic in the Stern source code though of the logs themselves.

Their README is also lacking screenshots sadly. @prune998 Do you happen to have a screenshot of Stern coloring the output? Could spark inspiration :)
