### ISSUE TITLE
Every line in server-dry-run is green

### ISSUE THREAD

**Issue by mattcockrell** [kubecolor/kubecolor#57]
# Expected Behavior

Colors match the behavior of other subcommands (apply, etc) where the unchanged/configured/etc word is highlighted

# Current Behavior

Every line ending in (server-dry-run) is colored green.

## Context

* Operating System: Windows 10
* kubectl version: 1.26
* kubecolor version: 0.2.2

**Comment by applejag** [comment]
Thanks for reporting this, @mattcockrell! We'll look into it when we have time.

If you want this sooner, you could also try making a PR to fix this.
