### ISSUE TITLE
colorizing events

### ISSUE THREAD

**Issue by mattcockrell** [kubecolor/kubecolor#61]
# Expected Behavior

'kubecolor events' will produce the same colorized output as 'kubecolor describe'

# Current Behavior

'kubecolor events' produces plain output

Output of 'kubecolor describe'
![image](https://github.com/kubecolor/kubecolor/assets/99686918/d81bdd6c-c058-4585-9b58-d9e1db3700bd)

Output of 'kubecolor events'
![image](https://github.com/kubecolor/kubecolor/assets/99686918/305c026a-9912-4fa7-a21f-089e47fbfd25)

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Windows 10
* kubectl version: 1.26
* kubecolor version: 0.2.2
* shell environment: Powershell 7.4.0

**Comment by applejag** [comment]
Did not know `kubectl events` was a thing. I've always used `kubectl get events`. This should definitely be fixed!

Thanks for reporting this, and extra thanks for providing screenshots @mattcockrell !

**Comment by mattcockrell** [comment]
Thanks for being so active. `kubectl events` is nice because you can add a `--for` parameter to target a specific resource. `kubectl events --for pod/podname` is what I was using when I noticed the missing color.

**Comment by semihbkgr** [comment]
Hi @applejag 
I can work on that.
It should be easy since there is already coloring functionality for `kubectl get events`.
