### ISSUE TITLE
Support for kubecolor using the oc command for OpenShift

### ISSUE THREAD

**Issue by kritag** [kubecolor/kubecolor#63]
# Expected Behavior

When the `oc` command is issued, it would have its output colorized.

# Current Behavior

Currently, output from the `oc` command isn't colorized.

## Context

I don't know how kubecolor works well enough to propose any fixes, but seeing that `oc` can be used interchangably with `kubectl` it would be nice to have colorized output those times I absolutely have to use the `oc` command rather than `kubectl`. I'd also rather have my environment set up with aliases and such using `oc` rather than `kubectl` since I work extensively with OpenShift clusters.

* Operating System: Arch Linux
* kubectl version: Client Version: v1.29.1
* kubecolor version: 0.2.2-1

**Comment by applejag** [comment]
Hello @kritag, thanks for reporting this!

Personally I don't know how different the `oc` commands are. I'm worried about inconsistencies, but in general, you should be able to make use of the `KUBECTL_COMMAND` environment variable. (<https://github.com/kubecolor/kubecolor?tab=readme-ov-file#specify-what-command-to-execute-as-kubectl>)

In short:

```bash
export KUBECTL_COMMAND=oc
alias oc=kubecolor

oc get pods
```

Kubecolor just executes kubectl (or what's in the `KUBECTL_COMMAND` env var) and passes it the same command-line arguments. Depending on the arguments, it applies coloring to the stdout and stderr based on what arguments you pass (e.g `get pods` => apply table coloring, `describe pod` => apply describe coloring).

Interested to hear if this works well for you. If so, then we can add the above snippet to the README for other's to see.

**Comment by kritag** [comment]
Hi, thanks for the prompt reply! indeed your solution works with oc as well! It also seems to colorize output of `oc` specific stuff like `oc get route`, which is very pleasant to see. Thanks a bunch!
