### ISSUE TITLE
Does not work with Termux on Android

### ISSUE THREAD

**Issue by onedr0p** [kubecolor/kubecolor#69]
# Expected Behavior

To work

# Current Behavior

Doesn't work

```
kubecolor get nodes
...

SIGSYS: bad system call
PC=0x133c0 m=0 sigcode=1

goroutine 1 [syscall]:
syscall.Syscall6(0x40000163f0?, 0x2b?, 0x2b?, 0x4000016420?, 0x0?, 0x4f?, 0xffffffffffffff9c?)
        /opt/hostedtoolcache/go/1.21.6/x64/src/syscall/syscall_linux.go:91 +0x2c fp=0x4000121af0 sp=0x4000121a60 pc=0x82a4c
syscall.faccessat2(0x40000163f0?, {0x40000163f0?, 0x7184ffd0b0?}, 0x1, 0xc0?)
        /opt/hostedtoolcache/go/1.21.6/x64/src/syscall/zsyscall_linux_arm64.go:33 +0x84 fp=0x4000121b60 sp=0x4000121af0 pc=0x813d4
syscall.Faccessat(0x40000163f0?, {0x40000163f0, 0x2b}, 0x1, 0x200)
        /opt/hostedtoolcache/go/1.21.6/x64/src/syscall/syscall_linux.go:167 +0x3c fp=0x4000121c50 sp=0x4000121b60 pc=0x805cc
internal/syscall/unix.Eaccess(...)
        /opt/hostedtoolcache/go/1.21.6/x64/src/internal/syscall/unix/eaccess_linux.go:10
os/exec.findExecutable({0x40000163f0, 0x2b})
        /opt/hostedtoolcache/go/1.21.6/x64/src/os/exec/lp_unix.go:31 +0x58 fp=0x4000121ca0 sp=0x4000121c50 pc=0xc39a8
os/exec.LookPath({0x11bc53, 0x7})
        /opt/hostedtoolcache/go/1.21.6/x64/src/os/exec/lp_unix.go:71 +0x1b8 fp=0x4000121d40 sp=0x4000121ca0 pc=0xc3c78
os/exec.Command({0x11bc53, 0x7}, {0x40000100d0, 0x2, 0x4000121f28?})
        /opt/hostedtoolcache/go/1.21.6/x64/src/os/exec/exec.go:419 +0x1cc fp=0x4000121dd0 sp=0x4000121d40 pc=0xc087c
github.com/kubecolor/kubecolor/command.Run({0x40000100d0?, 0x46788?, 0x400001e060?}, {0x14641c, 0x5})
        /home/runner/work/kubecolor/kubecolor/command/runner.go:59 +0x6c fp=0x4000121ec0 sp=0x4000121dd0 pc=0xe658c
main.main()
        /home/runner/work/kubecolor/kubecolor/main.go:15 +0x80 fp=0x4000121f30 sp=0x4000121ec0 pc=0xe73e0
runtime.main()
        /opt/hostedtoolcache/go/1.21.6/x64/src/runtime/proc.go:267 +0x2bc fp=0x4000121fd0 sp=0x4000121f30 pc=0x467bc
runtime.goexit()
        /opt/hostedtoolcache/go/1.21.6/x64/src/runtime/asm_arm64.s:1197 +0x4 fp=0x4000121fd0 sp=0x4000121fd0 pc=0x75094

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /opt/hostedtoolcache/go/1.21.6/x64/src/runtime/proc.go:398 +0xc8 fp=0x4000044f90 sp=0x4000044f70 pc=0x46be8
runtime.goparkunlock(...)
        /opt/hostedtoolcache/go/1.21.6/x64/src/runtime/proc.go:404
runtime.forcegchelper()
        /opt/hostedtoolcache/go/1.21.6/x64/src/runtime/proc.go:322 +0xb8 fp=0x4000044fd0 sp=0x4000044f90 pc=0x46a78
runtime.goexit()
        /opt/hostedtoolcache/go/1.21.6/x64/src/runtime/asm_arm64.s:1197 +0x4 fp=0x4000044fd0 sp=0x4000044fd0 pc=0x75094
created by runtime.init.6 in goroutine 1
        /opt/hostedtoolcache/go/1.21.6/x64/src/runtime/proc.go:310 +0x24

goroutine 3 [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /opt/hostedtoolcache/go/1.21.6/x64/src/runtime/proc.go:398 +0xc8 fp=0x4000045760 sp=0x4000045740 pc=0x46be8
runtime.goparkunlock(...)
        /opt/hostedtoolcache/go/1.21.6/x64/src/runtime/proc.go:404
runtime.bgsweep(0x0?)
        /opt/hostedtoolcache/go/1.21.6/x64/src/runtime/mgcsweep.go:280 +0xa0 fp=0x40000457b0 sp=0x4000045760 pc=0x333a0
runtime.gcenable.func1()
        /opt/hostedtoolcache/go/1.21.6/x64/src/runtime/mgc.go:200 +0x28 fp=0x40000457d0 sp=0x40000457b0 pc=0x28148
runtime.goexit()
        /opt/hostedtoolcache/go/1.21.6/x64/src/runtime/asm_arm64.s:1197 +0x4 fp=0x40000457d0 sp=0x40000457d0 pc=0x75094
created by runtime.gcenable in goroutine 1
        /opt/hostedtoolcache/go/1.21.6/x64/src/runtime/mgc.go:200 +0x6c

goroutine 4 [GC scavenge wait]:
runtime.gopark(0x4000028150?, 0x145478?, 0x1?, 0x0?, 0x4000002d00?)
        /opt/hostedtoolcache/go/1.21.6/x64/src/runtime/proc.go:398 +0xc8 fp=0x4000045f50 sp=0x4000045f30 pc=0x46be8
runtime.goparkunlock(...)
        /opt/hostedtoolcache/go/1.21.6/x64/src/runtime/proc.go:404
runtime.(*scavengerState).park(0x1fa2a0)
        /opt/hostedtoolcache/go/1.21.6/x64/src/runtime/mgcscavenge.go:425 +0x5c fp=0x4000045f80 sp=0x4000045f50 pc=0x30c6c
runtime.bgscavenge(0x0?)
        /opt/hostedtoolcache/go/1.21.6/x64/src/runtime/mgcscavenge.go:653 +0x44 fp=0x4000045fb0 sp=0x4000045f80 pc=0x311b4
runtime.gcenable.func2()
        /opt/hostedtoolcache/go/1.21.6/x64/src/runtime/mgc.go:201 +0x28 fp=0x4000045fd0 sp=0x4000045fb0 pc=0x280e8
runtime.goexit()
        /opt/hostedtoolcache/go/1.21.6/x64/src/runtime/asm_arm64.s:1197 +0x4 fp=0x4000045fd0 sp=0x4000045fd0 pc=0x75094
created by runtime.gcenable in goroutine 1
        /opt/hostedtoolcache/go/1.21.6/x64/src/runtime/mgc.go:201 +0xac

goroutine 5 [finalizer wait]:
runtime.gopark(0x40000445a8?, 0x713a4?, 0x1?, 0x45?, 0x7d324?)
        /opt/hostedtoolcache/go/1.21.6/x64/src/runtime/proc.go:398 +0xc8 fp=0x4000044580 sp=0x4000044560 pc=0x46be8
runtime.runfinq()
        /opt/hostedtoolcache/go/1.21.6/x64/src/runtime/mfinal.go:193 +0x108 fp=0x40000447d0 sp=0x4000044580 pc=0x271f8
runtime.goexit()
        /opt/hostedtoolcache/go/1.21.6/x64/src/runtime/asm_arm64.s:1197 +0x4 fp=0x40000447d0 sp=0x40000447d0 pc=0x75094
created by runtime.createfing in goroutine 1
        /opt/hostedtoolcache/go/1.21.6/x64/src/runtime/mfinal.go:163 +0x80

r0      0xffffffffffffff9c
r1      0x4000016450
r2      0x1
r3      0x200
r4      0x0
r5      0x0
r6      0x0
r7      0x1
r8      0x1b7
r9      0x2f7273752f73656c
r10     0x6d7265742e6d6f63
r11     0x73656c69662f7875
r12     0x6e69622f7273752f
r13     0x6c74636562756b2f
r14     0x18
r15     0x64656e6f2f736f70
r16     0x40001203a0
r17     0x4000121be0
r18     0x0
r19     0x0
r20     0x4000121b48
r21     0x7fec0091a8
r22     0x0
r23     0x0
r24     0x0
r25     0x0
r26     0x126308
r27     0x0
r28     0x40000021a0
r29     0x40001219f8
lr      0x1337c
sp      0x4000121a00
pc      0x133c0
fault   0x0
```

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Android using Termux
* kubectl version: 1.29.2
* kubecolor version: 0.2.2

**Comment by applejag** [comment]
Interesting case 🤔 thanks @onedr0p for reporting this!

It sounds like you're using the Linux build on an Android. In this case, I believe you should compile it with `GOOS=android`

Your logs also suggests that you're running this via GitHub Actions. So just to verify, could you try compiling kubecolor inside your GitHub Actions workflow?

Such as:

```yaml
steps:
  - uses: actions/checkout@v4
  - uses: actions/setup-go@v5
    with:
      go-version: '>=1.22.0'
  - run: go install github.com/kubecolor/kubecolor@latest
```

**Comment by onedr0p** [comment]
> Your logs also suggests that you're running this via GitHub Actions. So just to verify, could you try compiling kubecolor inside your GitHub Actions workflow?

Not sure where you got that impression, I downloaded the binary from GH releases and tried running it in Termux.

**Comment by applejag** [comment]
> Not sure where you got that impression, I downloaded the binary from GH releases and tried running it in Termux.

My bad! I got juked by the paths in the stack traces, like `/opt/hostedtoolcache/...` which is a GH Actions thing. But it's probably added from when the binary was built.

But still to just verify, could you try installing Go into your Termux and running:

```shell
go install github.com/kubecolor/kubecolor get nodes
```

If that works, then we'd know that we need to add an Android built to our releases

**Comment by onedr0p** [comment]
Yep that worked. I'm pretty curious why the Linux arm64 build won't work though? I downloaded a bunch of Kubernetes tools (kustomize, kubectl, talosctl, stern and more) and all I need to pull is the Linux arm64 variant. They don't appear to have a build specific for Android.

**Comment by applejag** [comment]
> Yep that worked. I'm pretty curious why the Linux arm64 build won't work though? I downloaded a bunch of Kubernetes tools (kustomize, kubectl, talosctl, stern and more) and all I need to pull is the Linux arm64 variant. They don't appear to have a build specific for Android.
> 
> I wonder if there's a fix in the code to remedy this instead?

Good point. And hopefully we can solve this without adding a new build target.

However compared to the other tools you listed, only kubecolor tries to run other executables. And the thing it's failing on here is a Linux syscall that Android does not allow.

Go itself seems to have solved this by only changing the Android builds (https://github.com/golang/go/issues/57393). 

Kubecolor is only using higher level functions ([`os.Command`](https://pkg.go.dev/os/exec#Command)), so we don't actually invoke the syscall ourselves. So updating this may be tricky.

I'm not able to debug and test solutions at the moment. But will come back to it when I find some time and lust. (We're also open to contributions if you want to give it a go 😉)

**Comment by applejag** [comment]
Though kubectl does occasionally execute external binaries, such as with kubectl plugins and credentials plugins. But they don't seem to provide a specific android binary. So might be worth looking into if they've come across this too and solved it without needing an Android build too.

**Comment by onedr0p** [comment]
No worries, I'll keep with the Go installed version for now as it works fine. Hopefully sometime can work out what's happening here. Thanks 🙏

**Comment by applejag** [comment]
I checked kubectl's source code, and they do not do anything special when it comes to handling `exec.LookPath` syscall on Android.

I also tried out Termux and saw that the binary used there was compiled with `GOOS=android`

```console
$ go version -m /data/data/com.termux/files/usr/bin/kubectl | grep GOOS
        build   GOOS=android
```

Termux seem to compile using `GOOS=android` for their own packages, installed via `pkg install kubectl`. ([Termux build script for kubectl here](https://github.com/termux/termux-packages/blob/e38984b9197b611528a24d93a95e96664935d6eb/packages/kubectl/build.sh)) Which also explains why `kubectl version` reports v0.0.0, as they're not building kubectl completely correctly.

Another possible workaround I found was to supply the absolute path to `kubectl`:

```bash
export KUBECTL_COMMAND=$(which kubectl)

# Should work fine
kubecolor get pods
```

Because it's the `exec.LookPath` that's trying to use an illegal syscall and thereby causing a panic. In `exec.Command` [only executes `exec.LookPath` if `filepath.Base(name) == name`](https://cs.opensource.google/go/go/+/refs/tags/go1.22.1:src/os/exec/exec.go;l=418-419;drc=f7f266c88598398dcf32b448bcea2100e1702630). Though I've not tested this.

---

Of course, a better option would be to get kubecolor added to the Termux packages, and let it get that Android build.

**Comment by onedr0p** [comment]
Looks to be working, thanks!
