### ISSUE TITLE
Log lines are displayed in green

### ISSUE THREAD

**Issue by semihbkgr** [kubecolor/kubecolor#70]
# Expected Behavior

It would be preferable to colorize specific keywords, such as log severity levels, in a different color, but only when the logs themselves are not already colored.

# Current Behavior

Currently all log lines are presented in green.
It doesn't look good when they are already colored by default.

```bash
$ kubectl logs hazelcast
```

<img width="1726" alt="Screenshot 2024-03-03 at 9 48 25 PM" src="https://github.com/kubecolor/kubecolor/assets/55327573/bd8443e1-636b-44d9-944a-e8351c9ff008">

```bash 
$ kubecolor logs hazelcast
```

<img width="1726" alt="Screenshot 2024-03-03 at 9 48 05 PM" src="https://github.com/kubecolor/kubecolor/assets/55327573/aaea1284-2acd-4677-b641-1457ca8a7521">

## Context

* Operating System: darwin/arm64
* kubectl version: v1.27.2
* kubecolor version: v0.2.2

**Comment by applejag** [comment]
Hello @semihbkgr, thanks for reporting this!

I believe this is too similar to #51, so I'm closing this as a duplicate.
