### ISSUE TITLE
Fish Support

### ISSUE THREAD

**Issue by wcasanova** [kubecolor/kubecolor#87]
> Fish
> Fish completion is officially unsupported by kubectl, so it is unsupported by kubecolor as well.

https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#kubectl-autocompletion-1

`kubectl completion fish | source`

**Comment by applejag** [comment]
Ah would you look at that. Thanks @wcasanova for pointing this out.

Aa you might expect, none of us maintainers use fish so we don't stay that up to date on that topic.
